cobby/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('user.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
    path('', include('makgeolli.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

makgeolli/urls.py
from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static
from makgeolli import views
app_name = 'makgeolli'
urlpatterns = [
    # 221018 최해민 Makgeolli url 추가
    path('makgeolli/', views.makgeolli, name='makgeolli'),
    path('makgeolli/<int:id>', views.makgeolli_detail, name='detail'),

]

post/urls.py
from django.urls import path
from post import views

app_name = 'post'

urlpatterns = [
    path('search/', views.Post_search, name='post_search'),
    path('comment/delete/<int:pk>/', views.comment_delete, name='delete'),
    path('comment/<int:id>/', views.create_comment, name= 'create_comment'), 
    path('edit/<int:id>/', views.edit, name = 'comment_edit'),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user import views


app_name = 'user'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    
    # 221020 최해민 search 추가
    path('upload/', views.upload, name='upload'),
]

makgeolli/models.py
from django.db import models
import os
from django.conf import settings



# 221018 최해민 막걸리 모델 추가
class Makgeolli(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField(upload_to='makgeolli/', blank=True, null=True)
    desc = models.TextField()
    
    # 221018 최해민 막걸리 객체 삭제하면, media파일도 삭제
    def delete(self, *args, **kwargs):
        super(Makgeolli, self).delete(*args, **kwargs)
        os.remove(os.path.join(settings.MEDIA_ROOT, self.image.path))
    
    def __str__(self):
        return str(self.name)

# 221019 사용자가 막걸리 사진을 업로드 하는 기능. 
class Cobby(models.Model):
    image = models.ImageField(blank=True , null=True, upload_to='cobby/')
    name = models.CharField(max_length=1)

post/models.py
from django.db import models
from user.models import User
from makgeolli.models import Makgeolli


class Comment(models.Model):
    content = models.CharField(max_length=80)
    create_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Makgeolli, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return str(self.content)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    
    phonenum = models.CharField(max_length=20, verbose_name='전화번호')
    email = models.EmailField(max_length=100, blank=False ,verbose_name='이메일')

makgeolli/views.py
from django.shortcuts import render, get_object_or_404 ,redirect
from makgeolli.models import Makgeolli
from .models import Cobby

# 221018 최해민 막걸리 리스트 페이지 함수 추가
def makgeolli(request):
    makgeolli_list = Makgeolli.objects.all()
    return render(request, 'makgeolli/makgeolli.html', {'makgeolli_list':makgeolli_list})

def makgeolli_detail(request, id):
    makgeolli = get_object_or_404(Makgeolli, id=id)
    return render(request, 'makgeolli/makgeolli_detail.html', {'makgeolli':makgeolli})

# 221019 최신욱 사용자 Image 저장.
def Image(request):
    if request.method == 'GET':
        return render(request, 'post/index.html')
    if request.method =='POST':
        user_image = Cobby()
        user_image.image = request.FILES.get('images', '')
        user_image.save()
        return redirect('makgeolli:detail')

post/views.py
from ast import If
from django.shortcuts import HttpResponse, render, redirect
from django.http import HttpResponse
from post.models import Comment
from makgeolli.models import Makgeolli

# 장혜림_댓글 작성 함수 
def create_comment(request, id):
    if request.method == 'GET':
        user = request.user.is_authenticated
        if user:
            article = Makgeolli.objects.get(id=id)
            return render(request, 'makgeolli_detail.html', {"article":article})
        else:
            return HttpResponse("로그인 후 이용해주세요")
    
    elif request.method == 'POST':
        user = request.user
        contents = Comment()
        contents.author = user
        contents.content = request.POST.get('content','')
        contents.article = Makgeolli.objects.get(id=id)
        contents.save()
        print(request.POST.get('content',''))
        return redirect(f'/makgeolli/{id}')
        

# 장혜림_댓글 수정 함수
def edit(request, id):
    if request.method == 'GET':
        content = Comment.objects.get(id=id)             
        context = {                                         
            'content': content,
        }
        return render(request, 'comment_edit.html', context)
    if request.method == 'POST':
        user = request.user
        contents = Comment.objects.get(id=id)
        contents.author = user
        contents.content = request.POST.get('contents','') #htm에서 쓰이는 이름
        contents.save()
        return redirect(f'/makgeolli/{contents.article.id}')        

   
    
    
    


def comment_delete(request,pk):
    comments = Comment.objects.get(pk=pk)
    
    """ 
    2022.10.17 최신욱
    댓글 삭제 함수입니다.

    Args:
        request : 사용자가 댓글 삭제를 요청했을 때 입력된 값. (정보)
        pk : 댓글 생성시 발급되는 고유 id 값

    Returns:
            사용자가 보낸 요청이 'POST' 일 경우 댓글을 삭제 한 뒤 ''로 이동합니다.
            그 외 모든 요청을 보내올 경우 '' 를 보여줍니다.
    """
    comments.delete()
    return redirect(f'/makgeolli/{comments.article.id}')
    



def Post_search(request):
    """
    2022.10.17 최신욱
    게시글 검색 함수입니다.
    현재는 title로만 검색이 가능합니다.

    Args:
        request : 사용자가 검색을 요청했을 때 입력된 값.

    Returns:
            검색을 요청한 사용자의 입력 값이 title=search 일치한다면, 일치하는 정보들만 post_search.html를 rander합니다.
    """

    post_list = Makgeolli.objects.all()
    search = request.GET.get('search' ,'')
    if search :
        post_list = post_list.filter(name__icontains=search)
        post_id = post_list.values()[0]['id']
        print(post_id)
    return redirect(f'/makgeolli/{post_id}')
    # <최종적으로 해당 지평생막걸리 페이지로 바로 이동.>

user/views.py
from django.shortcuts import render , redirect
from makgeolli.models import Cobby, Makgeolli
import easyocr
from urllib import parse
from pprint import pprint

def index(request):
    page = request.GET.get('page', '1')  # 메인페이지
    return render(request, 'user/index.html')      

from django.shortcuts import render,redirect
from user.models import User

# Create your views here.
def signup(request): #20221018 문규빈 회원가입 기능
    if request.method == 'GET':
        return render(request, 'user/signup.html') #셋팅에 따라 형식이 바뀔 수 있음

    
    if request.method == 'POST':
        user = User()
        user.username = request.POST.get('username','')
        user.phonenum = request.POST.get('phonenum','')
        user.email = request.POST.get('email','')
        user.password = request.POST.get('password','')
        
        if user.username == "" or user.password == "" or user.email == "" or user.phonenum == "": #빈칸이 있을 때
            print(user.username)
            print(user.phonenum)
            print(user.email)
            print(user.password)
            print('1')
            return render (request, 'user/signup.html', {'error' : '입력창을 확인해주십시오.'})
            
        if User.objects.filter(username = user.username).exists(): #아이디 중복체크  exists에 () 꼭 붙일 것!
            print(user.username)
            return render (request, 'user/signup.html',{'error' : '사용할 수 없는 아이디 입니다.'})
        else:
            print("3")        
            user.set_password(user.password) #비밀번호 암호화
            user.save()
            return redirect('/login/')
        

# 221019 최해민 upload, EasyOCR 추가
def upload(request):
    if request.method == 'GET':
        return render(request, 'user/base.html')
    
    if request.method == 'POST':
        file = request.FILES['product_image']
        new_file = Cobby()
        new_file.image = file
        new_file.save()
    
        reader = easyocr.Reader(['ko'], gpu=True) # 'ko' : 한글로 설정
        result_list = reader.readtext(parse.unquote(new_file.image.url[1:]))
        pprint(result_list)
    
        name = '' # 찾은 text들을 다 더할 빈 문자열
        for result in result_list:
            name += result[1] # text들을 name에 다 더해준다.
        mak_list = Makgeolli.objects.all()
        for mak in mak_list:
            if mak.name in name:
                return redirect(f'/makgeolli/{mak.id}')
        else:
            return render(request, 'user/base.html', {'error':"다른 이미지 파일을 업로드 해주세요."})

post/templates/makgeolli_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lobster&display=swap');

        *{
            box-sizing:border-box;
            margin:0;
            padding:0;
        }

        body{
            background:#fafafa;
        }

        ol, ul {
            list-style:none;   
        }

        p, span, div, a{
            font-family: sans-serif;
        }

        button{
            border:none;
        }

        a{
            color:#000;
            text-decoration:none;
        }

        button{
            background: none;
            cursor: pointer;
        }

        h1{
            color:#262626;
            font-family:'Lobster', cursive;
            font-weight:100;
            line-height: 1; 
        }

        input, textarea{
            outline:none;
        }

        .comments{
            margin : auto;
            justify-content: center;
        }

        .txt_id{
            font-size: 1.3rem;
            font-weight: bold;
            margin: 0.5rem 1rem 0.5rem 0;
        }

    </style>
</head>
<body>
    <div style="width: 80%;" class="container">
        <div class="row fs-1">
            <p>{{ makgeolli.name }}막걸리</p>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <img style='max-width:80%; 'class="rounded img-responsive mx-auto d-block" src="{{ makgeolli.image.url }}" alt="{{ makgeolli.name }}">
            </div>
        </div>
        <div class="row">
            <br>
        </div>
        <div class="row fs-5">
            <div class="col">
                <p> Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis pariatur voluptas recusandae ullam accusamus neque impedit inventore, perspiciatis deleniti officia voluptates. Iusto ullam eaque architecto dicta sit, accusamus impedit aperiam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor accusantium architecto nihil voluptate magni hic consequatur. Dolor quaerat itaque facere, soluta ab impedit, alias laborum ratione sit perspiciatis commodi ducimus!</p>
            </div>
        </div>
        <div class="row">
            <hr>
        </div>
    
    

        <!--#################################-->
        {{Makgeolli.comment_set.all}}
        {% for comment in Makgeolli.comment_set.all %}
        <h4>제목: {{ comment.user }}</h4>
        <h4>내용: {{ comment.content }}</h4>
        <div class="comments">
            <div id="listComment" class="list_comment">
                <form action="{% url 'post:create_comment' %}" method="POST">
                    {% csrf_token %}
                    <p class="txt_comment">
                    <span>
                        <a href="#n" class="txt_id">Nol_bu</a>
                        <span>아무거나 먹어도 맛있답니다.</span>
                    </span>
                    <i style="color: green; margin-left: 1rem;" class="bi bi-pencil-square"></i>
                    <i style="color: red; margin-left: 1rem;"class="bi bi-x-square"></i>
                    </p>
            </div>
        </div><!-- comments div end -->
        {% endfor %}
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="댓글을 입력해주세요." aria-describedby="button-addon2">
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">작성</button>
        </div>
    </div><!-- container div end -->

</body>
</html>

templates/makgeolli/makgeolli.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        a {
            color: black;
            text-decoration: none;
        }
        .nav {
            background-color: rgb(199, 199, 199);
            height: 80px;
            width: 100%;
            display: flex;
            align-content: center;
            justify-content: space-between;
            margin-bottom: 2rem;
          }
        .nav_a{
            padding: 1rem;
        }
        .nav > a:first-child{
            margin-right: auto;
        }
        .sign_div {
            width: fit-content;
            height: fit-content;
            display: flex;
            align-content: center;
            padding: 1rem;
        }
        .card-img-top {
            width: 100%;
            height: 18rem;
            overflow: hidden;
        }
        .container {
            width: 100%;
            display: flex;
            flex-wrap: wrap;
            justify-content: baseline;
        }
        .card {
            width: 20%;
            height:fit-content;
            overflow: hidden;
            margin: 2rem;
        }
    </style>
</head>
<body>
    <div class="nav">
        <a class="nav_a" href="/">Home</a>
        <a class="nav_a" href="{% url 'makgeolli:makgeolli'%}">막걸리들</a>
        <div class="sign_div">
            {% if user.is_authenticated %}
            <a href="{% url 'user:logout' %}">{{ user.username }} (로그아웃)</a>
            {% else %}
            <a href="{% url 'user:login' %}">로그인</a>
            {% endif %}
        </div>
    </div><!-- nav div end -->
    
    <div class="container">
        {% for makgeolli in makgeolli_list %}
        <div class="card">
            <img src="{{ makgeolli.image.url }}" class="card-img-top" alt="{{ makgeolli.name }}">
            <div class="card-body">
                <h5 class="card-title">{{ makgeolli.name }}</h5>
                <p class="card-text">{{ makgeolli.desc }}</p>
                <a href="{% url 'makgeolli:detail' makgeolli.id %}" class="btn btn-primary">상세보기</a>
            </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>

templates/makgeolli/makgeolli_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css" />
  <style>
    @import url("https://fonts.googleapis.com/css2?family=Lobster&display=swap");

    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      background: #fafafa;
    }

    ol,
    ul {
      list-style: none;
    }

    p,
    span,
    div,
    a {
      font-family: sans-serif;
    }

    button {
      border: none;
    }

    a {
      color: #000;
      text-decoration: none;
      padding: 1rem;
    }

    button,
    i {
      background: none;
      cursor: pointer;
    }

    h1 {
      color: #262626;
      font-family: "Lobster", cursive;
      font-weight: 100;
      line-height: 1;
    }

    input,
    textarea {
      outline: none;
    }

    .comments {
      margin: auto;
      justify-content: center;
    }

    .txt_id {
      font-size: 1.3rem;
      font-weight: bold;
      margin: 0.5rem 1rem 0.5rem 0;
    }

    .form-control {
      width: 20rem;
    }

    .nav {
      background-color: rgb(199, 199, 199);
      height: 80px;
      width: 100%;
      display: flex;
      align-content: center;
      justify-content: space-between;
    }
    .sign_div{
      width: fit-content;
      height: fit-content;
      display: flex;
      align-content: center;
    }
  </style>
</head>

<body>
  <div class="nav">
    <a href="/">Home</a>
    <div class="sign_div">
      {% if user.is_authenticated %}
      <a href="{% url 'user:logout' %}">{{ user.username }} (로그아웃)</a>
      {% else %}
      <a href="{% url 'user:login' %}">로그인</a>
      {% endif %}
    </div>
  </div><!-- nav div end -->

  <div style="width: 80%;" class="container">
    <div class="row fs-1" style="padding: 2rem 0 1rem;">
      <p>{{ makgeolli.name }}막걸리</p>
    </div>
    <div class="row justify-content-md-center">
      <div class="col-md-auto">
        <img style="max-width: 80%" class="rounded img-responsive mx-auto d-block" src="{{ makgeolli.image.url }}"
          alt="{{ makgeolli.name }}" />
      </div>
    </div>
    <div class="row">
      <br />
    </div>
    <div class="row fs-5">
      <div class="col">
        <p>{{ makgeolli.desc }}</p>
      </div>
    </div>
    <div class="row">
      <hr />
    </div>


       
        {% for comment in makgeolli.comment_set.all %}
        <div class="comments">
            <div id="listComment" class="list_comment">
                    <p class="txt_comment">
                    <span>
                        <a href="#" class="txt_id"> {{comment.author}} </a>
                        <span>{{comment.content}}</span>
                    </span>
                    {% if comment.author == request.user %}
                    <i class="bi bi-pencil-square" style="color: green; margin-left: 1rem;" onclick="location.href='{% url 'post:comment_edit' comment.id %}';">
                    </i>
                    <i style="color: red; margin-left: 1rem;"class="bi bi-x-square" onclick="location.href='{% url 'post:delete' comment.id %}';"></i>
                    </p>
                    {% endif %}
            </div>
        </div><!-- comments div end -->
        {% endfor %}
        <div class="input-group mb-3">
            <form class="d-flex" action="{% url 'post:create_comment' makgeolli.id %}" method="POST">
                {% csrf_token %}
            <input name = "content" type="text" class="form-control" placeholder="댓글을 입력해주세요." aria-describedby="button-addon2">
            
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">작성</button>
            
            </form>

        </div>
  </div>
  <!-- container div end -->
</body>

</html>

user/templates/user/base.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>코삐</title>
  </head>
  <style>
    @font-face {
      font-family: "WandohopeB";
      src: url("https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10@1.0/WandohopeB.woff")
        format("woff");
      font-weight: normal;
      font-style: normal;
    }
    * {
      margin: 0 auto;
    }
    .ui {
      background: rgb(199, 199, 199);
      height: 80px;
      margin-top: 0px;
    }
    .ui_search {
      height: 40px;
      width: 420px;
      position: absolute;
      top: 20px;
      left: 36%;
      display: flex;
    }
    .ui_login {
      background: rgb(199, 199, 199);
      height: 40px;
      width: 150px;
      position: absolute;
      left: 80%;
      margin-top: 30px;
    }
    .ui_login > a {
      color: black;
    }
    .search {
      width: 300px;
      height: 40px;
    }
    .img_file {
      width: 300px;
      height: 50px;
      position: absolute;
      left: 60.5%;
    }

    input[type="file"]::file-selector-button {
      width: 100px;
      height: 40px;
    }

    .main_box {
      width: 100%;
      height: 500px;
      float: left;
    }
    .post_box {
      width: 450px;
      height: 300px;
      background: rgb(103, 86, 86);
      margin-top: 5%;
    }
    .button1 {
      position: absolute;
      margin-bottom: 300px;
      width: 80px;
      height: 40px;

    }
    .form-group {
      margin-left: 80px;
      width: 50px;
    }
    .img_box {
      position: relative;
      width: 500px;
      height: 500px;
      top: 28px;
    }
    #image_container {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
    }

    #image_container > img {
      max-width: 500px;
      max-height: 500px;
      min-width: 500px;
      object-fit: contain;
    }
    .upload_btn {
      position: absolute;
      width: 450px;
      height: 50px;
      margin-top: 50px;
      left: 34.5%;
      border: none;
      border-radius: 10px;
      font-size: 13pt;
    }

    .upload_btn:hover {
      border: 1px solid black;
      cursor: pointer;
    }
    .error{
      width: 450px;
      height: 50px;
      position: absolute;
      top: 85%;
      left: 34.5%;
      display: flex;
      justify-content: center;
      align-items: center;
      border-radius: 1rem;
      background-color: rgb(255, 100, 100);
      color: white;
      margin: 1rem 0;
    }
  </style>
  <body>
    <div class="ui">
      <div class="ui_search">
        <form action="{% url 'post:post_search' %}" method="GET">
        <input
          type="search"
          name='search'
          placeholder="막걸리 이름 검색하기"
          class="search"
        />
        <button type="submit" class="button1">검색</button>
        </form>
        <div class="form-group">
          <form
            action="{% url 'user:upload' %}"
            method="post"
            enctype="multipart/form-data"
          >
            {% csrf_token %}
            <input
              class="form-control form-control-user"
              type="file"
              name="product_image"
              id="product_image"
              onchange="setThumbnail(event);"
            />
          
        </div>
      </div>

      <div class="ui_login">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'user:logout' %}"
          >{{ user.username }} (로그아웃)</a
        >
        {% else %}
        <a class="nav-link" href="{% url 'user:login' %}">로그인</a>
        {% endif %}
      </div>
    </div>
    <div class="img_box"><div id="image_container"></div></div>
    <button type="submit" class="upload_btn">업로드</button>
  </form>
  {% if error %}
  <div class="error">
    <p>{{ error }}</p>
  </div>
  {% endif %}

  </body>

  <script>
    function setThumbnail(event) {
      var reader = new FileReader();

      reader.onload = function (event) {
        var img = document.createElement("img");
        img.setAttribute("src", event.target.result);
        img.setAttribute("class", "col-lg-6");
        document.querySelector("div#image_container").appendChild(img);
      };

      reader.readAsDataURL(event.target.files[0]);
    }
  </script>
</html>

user/templates/user/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

user/templates/user/index.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>코삐</title>
  </head>
  <style>
    @font-face {
      font-family: "WandohopeB";
      src: url("https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10@1.0/WandohopeB.woff")
        format("woff");
      font-weight: normal;
      font-style: normal;
    }
    * {
      margin: 0 auto;
    }
    .ui {
      background: rgb(199, 199, 199);
      height: 80px;
    }
    .ui_search {
      background: rgb(255, 255, 255);
      height: 40px;
      width: 300px;
      position: absolute;
      left: 40%;
      display: flex;
    }
    .ui_login {
      background: rgb(199, 199, 199);
      width: 150px;
      position: absolute;
      left: 80%;
      top: 4%;
    }
    .ui_login > a {
      color: black;
    }

    .borad {
      background: rgb(255, 255, 255);
      height: 100vh;
    }
    .korea {
      position: absolute;
      width: 500px;
      left: 55%;
      margin-top: 20px;
    }
    .title {
      font-family: "WandohopeB";
      font-size: 40px;
      position: absolute;
      left: 27%;
      width: 40%;
      top: 20%;
      writing-mode: vertical-lr;
    }
    .title strong {
      font-size: 100px;
    }
    .search {
      width: 257px;
      height: 40px;
    }
    .img_file {
      width: 300px;
      height: 50px;
      position: absolute;
      left: 60.5%;
    }
    .img2 {
      height: 500px;
      margin-top: 50px;
    }

    .search_icon {
      width: 50px;
      height: 50px;
      background: url(/static/imgs/search.png) no-repeat center;
      background-size: contain;
      border: none;
      margin-left: 50%;
      margin-top: 12px;
      cursor: pointer;
    }
  </style>
  <body>
    <div class="ui">
      <a href="{% url 'user:upload' %}">
        <button class="search_icon"></button
      ></a>
      <div class="ui_login">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'user:logout' %}"
          >{{ user.username }} (로그아웃)</a
        >
        {% else %}
        <a class="nav-link" href="{% url 'user:login' %}">로그인</a>
        {% endif %}
      </div>
    </div>

    <div class="borad">
      <div class="korea">
        <img src="static/imgs/korea.jpg" width="70%" />
      </div>
      <div class="title">
        <img class="img2" src="/static/imgs/img2.png" />
        <p><strong>코</strong>가<strong>삐</strong>뚤어지게</p>
      </div>
    </div>
  </body>
</html>